name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-and-test:
    name: Run Lint and Tests
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        go-version: [1.23.4]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v4

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-

      - name: Install golangci-lint
        run: make $(GOLANGCI_LINT)

      - name: Run Lint
        run: make lint

      - name: Build Project
        run: make build

      - name: Run Tests
        run: make test